version: "3.9"

services:
  
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_PORT}:80 

  php:
    container_name: ${APP_NAME}_php
    image: php:fpm-alpine
    volumes:
      - ./app:/var/www/html    
